project_name: "updater"
builds:
  - id: updater
    binary: updater
    main: ./cmd/updater
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      post: ./scripts/codesign.sh {{ .Path }}
archives:
  - replacements:
      386: i386
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
